### PR TITLE
Lock Node

### PR DESCRIPTION
**Pull request by rgerrans**
Everything seems to be testing out right on my system.

A couple of quick notes:
- I changed the configuration layout of the html file for the Lock node config. If you prefer a different structure, please feel free to edit. Or if you like this structure, I'm happy to apply it to the other nodes.
- I couldn't understand the code well enough to figure how to block lock/unlock around a `deviceJammingDetected` error response, thought I kind of assumed that would have been handled by Google to not lock/unlock if isJammed is set to True?
- I did have a situation where I had updated the .ts file for the node and it cleared my message payload settings. Didn't try to replicate but something to be aware of if we update an existing node .ts file. Not sure if there is something I missed in the code to prevent this.

### CODE REVIEW

**Comment by rgerrans** [comment]
@andrei-tatar I realized this never got pulled. Seems to be working fine on my deployment. Let me know any issues or concerns.

**Comment by rgerrans** [comment]
@andrei-tatar Let me know if I need to do anything else to this for you to pull (other than clean up the one conflict with the version number)?

**Comment by andrei-tatar** [comment]
@rgerrans  did you manage to test it? I think it looks good. I can merge it once the conflict is resolved.

**Comment by rgerrans** [comment]
I've been using it for 2 1/2 months and seems to work fine. I fixed the version number in my branch. so should be good to go. I did want to flag my earlier comment:

> - I changed the configuration layout of the html file for the Lock node config. If you prefer a different structure, please feel free to edit. Or if you like this structure, I'm happy to apply it to the other nodes.

**Comment by andrei-tatar** [comment]
@rgerrans merged and published 0.0.33
Thanks for the contribution! :)

**Comment by rgerrans** [comment]
@andrei-tatar Happy to help. I need to get back on the fan work one of these days when life slows down a little....Thanks for all your work getting this up and maintaining it.

**Pull request merged**
